version: 1.0.{build}

branches:
  only:
    - release
  except:
    - master
    - fpc

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# shallow_clone: true

matrix:
  fast_finish: true

platform:
  - x86

configuration:
  - Release

environment:
  BOOTSTRAP_PATH: '%APPVEYOR_BUILD_FOLDER%\bootstrap'
  BINW32_PATH: '%APPVEYOR_BUILD_FOLDER%\binw32'
  BOOTSTRAP_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/bootstrap.7z'
  BINW32_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/binw32.7z'
  FPC_CONFIGURE_DL: 'https://raw.githubusercontent.com/newpascal/npbuild/master/configure.bat'

# debug rdp 
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - appveyor DownloadFile %BOOTSTRAP_DL%
  - appveyor DownloadFile %BINW32_DL%
  - 7z x bootstrap.7z -o%APPVEYOR_BUILD_FOLDER% -y
  - 7z x binw32.7z -o%APPVEYOR_BUILD_FOLDER% -y
  - git archive --format zip --output fpcsrc.zip release
  - 7z d fpcsrc.zip appveyor.yml

build_script:
  - SET ORIGINAL_PATH=%PATH%
  - SET PATH=%BOOTSTRAP_PATH%;%BINW32_PATH%;%WINDIR%\System32
  - make clean all

after_build:
  - make install INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\freepascal\fpc
  - SET PATH=%ORIGINAL_PATH%
  - appveyor DownloadFile %FPC_CONFIGURE_DL% -FileName %APPVEYOR_BUILD_FOLDER%\freepascal\configure.bat
  - 7z a -tzip fpc.zip %APPVEYOR_BUILD_FOLDER%\freepascal

# debug rdp 
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: fpc.zip
    name: fpc
  - path: fpcsrc.zip
    name: fpcsrc

deploy:
  release: fpc4np-v$(appveyor_build_version)
  description: 'Release of FreePascal compiler for NewPascal'
  provider: GitHub
  auth_token:
    secure: 0zjNX5MmwwPNlCpgGKHe44W2flr5RdJm1uqe7poKPfnUDQYXzpgGOVPTU7pLVY0s
  artifact: fpc,fpcsrc
  draft: false
  prerelease: false
  on:
    branch: release                 # release from master branch only
    appveyor_repo_tag: false       # ?deploy on tag push only

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# deploy: off